#!/usr/bin/env bash
# This script gives information about the "school" file

filename="school"

if [ -a "$filename" ]
then
	echo "school file exists"
	if [ -s "$filename" ]
	then
	    echo "school file is not empty"
	else
	    echo "school file is empty"
	fi

	if [ -f "$filename" ]
	then
	    echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
